### ISSUE TITLE
about code

### ISSUE THREAD

**Issue by njnj0314** [pvnieo/SURFMNet-pytorch#5]
Hello, this code doesn't seem to have a test section.

**Comment by pvnieo** [comment]
yes, 

this is not an official implementation, and it's not maintained anymore. The official implementation is in tensorflow, and available [here](https://github.com/LIX-shape-analysis/SURFMNet).

You can get inspiration for test section from [here](https://github.com/nmwsharp/diffusion-net/tree/master/experiments/functional_correspondence).

Closing the issue. Feel free to get back if you have further questions.
